import type { CaptureEvent, StoredSession } from './types';
const literal = (s: unknown) => JSON.stringify(String(s ?? ''));
export function generatePlaywright(session: Pick<StoredSession, 'url' | 'title'>, events: CaptureEvent[]) {
    let input = 0;
    const initialUrl = events.find(event => event.kind === 'navigation')?.data.url || session.url;
    const lines = ["import { test, expect } from '@playwright/test';", '',
        '// Generated by ReproLab. Review selectors and add product-specific assertions.',
        '// Input values were NEVER recorded; supply safe fixture values in environment variables.',
        '// Authenticated apps need your own Playwright storageState fixture.',
        `test(${literal(session.title)}, async ({ page }) => {`,
        '  const runtimeErrors = [];', '  const serverFailures = [];',
        "  page.on('pageerror', error => runtimeErrors.push(error.message));",
        "  page.on('response', response => { if (response.status() >= 500) serverFailures.push(response.url()); });",
        `  await page.goto(process.env.REPRO_START_URL || ${literal(initialUrl)});`];
    for (const e of events) {
        const s = String(e.data.selector ?? '');
        if (e.kind === 'click' && s)
            lines.push(`  await page.locator(${literal(s)}).click();`);
        if (e.kind === 'input' && s) {
            input++;
            lines.push(`  const value${input} = process.env.REPRO_INPUT_${input};`, `  if (value${input} === undefined) throw new Error('Set REPRO_INPUT_${input} to a safe test fixture value.');`);
            const type = String(e.data.inputType);
            if (type === 'checkbox' || type === 'radio')
                lines.push(`  await page.locator(${literal(s)}).setChecked(value${input} === 'true');`);
            else if (type === 'select-one' || type === 'select-multiple')
                lines.push(`  await page.locator(${literal(s)}).selectOption(value${input});`);
            else
                lines.push(`  await page.locator(${literal(s)}).fill(value${input});`);
        }
    }
    lines.push('', '  // Wait for application-specific completion here (replace the generic settle wait).', '  await page.waitForTimeout(500);', "  expect(runtimeErrors, 'No uncaught runtime errors after reproduction').toEqual([]);", "  expect(serverFailures, 'No failed server requests after reproduction').toEqual([]);", '});', '');
    return lines.join('\n');
}
export function issueMarkdown(session: Pick<StoredSession, 'title' | 'url' | 'browser' | 'release' | 'duration'>, events: CaptureEvent[]) {
    const code = (s: unknown) => String(s ?? '').replace(/`/g, "'").replace(/[\r\n]/g, ' ');
    const errors = events.filter(e => e.kind === 'error'), network = events.filter(e => e.kind === 'network' && Number(e.data.status) >= 400);
    return `## ${code(session.title)}\n\nCaptured with ReproLab. Review this report before sharing externally.\n\n` +
        `**Page:** ${code(session.url)}\n**Release:** ${code(session.release) || 'not set'}\n**Browser:** ${code(session.browser)}\n**Duration:** ${(session.duration / 1000).toFixed(1)}s\n\n` +
        '### Steps to reproduce\n' + events.filter(e => ['click', 'input', 'navigation', 'marker'].includes(e.kind)).map((e, i) => `${i + 1}. ${(e.at / 1000).toFixed(1)}s — ${e.kind}: ${code(e.data.label || e.data.selector || e.data.url)}${e.kind === 'input' ? ' (value redacted; add a safe fixture)' : ''}`).join('\n') +
        '\n\n### Observed errors\n' + (errors.map(e => `- ${code(e.data.name)}: ${code(e.data.message)}`).join('\n') || 'No uncaught errors recorded.') +
        '\n\n### Failed requests\n' + (network.map(e => `- ${code(e.data.method)} ${code(e.data.url)} → ${e.data.status}`).join('\n') || 'No failed HTTP responses recorded.') +
        '\n\n### Expected behavior\nDescribe the expected outcome.\n\n### Privacy\nInputs masked; query strings, credentials and network bodies excluded. Visual reconstruction is not a pixel-perfect recording.\n';
}
